### ISSUE TITLE
Issue introduced on 2.1.22 - Uncaught (in promise) TypeError: Cannot read property 'startsWith' of null

### ISSUE THREAD

**Issue by cacoze** [labcodes/react-redux-api-tools#14]
I'm getting an error `Uncaught (in promise) TypeError: Cannot read property 'startsWith' of null` when processing a 204 (No content) response, because it seems that we're not supposed to expect any `content-type` for that status_code.

Screenshots:
![image](https://user-images.githubusercontent.com/1657123/85429634-65069800-b555-11ea-9cee-940b50eee178.png)

**Comment by lucianoratamero** [comment]
Thanks for opening the issue @cacoze !
I'll work on it this week, should be fairly straightforward :]
